Failures in [node-test-pull-request/69552](https://ci.nodejs.org/job/node-test-pull-request/69552/) to [node-test-pull-request/69650](https://ci.nodejs.org/job/node-test-pull-request/69650/) that failed 2 or more PRs
(Generated with `ncu-ci walk pr --stats=true --markdown reports/2025-10-10.md`)

| UTC Time         | RUNNING | SUCCESS | UNSTABLE | ABORTED | FAILURE | Green Rate |
| ---------------- | ------- | ------- | -------- | ------- | ------- | ---------- |
| 2025-10-10 00:11 | 1       | 0       | 28       | 4       | 67      | 0.00%      |


### Jenkins Failure

| Reason | <code>Backing channel 'JNLP4-connect connection from ... is disconnected.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60142/](https://ci.nodejs.org/job/node-test-pull-request/69594/), [https://github.com/nodejs/node/pull/60144/](https://ci.nodejs.org/job/node-test-pull-request/69595/)) |
| Appeared | [test-ibm-alpine321_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-last-latest-x64/66896/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69594/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69595/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-last-latest-x64/66896/console">Example</a></summary>

```
java.io.IOException: Backing channel 'JNLP4-connect connection from 9.1a.7534.ip4.static.sl-reverse.com/52.117.26.9:57592' is disconnected.
	at hudson.remoting.RemoteInvocationHandler.channelOrFail(RemoteInvocationHandler.java:227)
	at hudson.remoting.RemoteInvocationHandler.invoke(RemoteInvocationHandler.java:306)
	at jdk.proxy2/jdk.proxy2.$Proxy218.isAlive(Unknown Source)
	at hudson.Launcher$RemoteLauncher$ProcImpl.isAlive(Launcher.java:1227)
	at hudson.Launcher$RemoteLauncher$ProcImpl.join(Launcher.java:1219)
```
</details>

-------

| Reason | <code>Build timed out (after 60 minutes). Marking the build as failed.</code> |
| - | :- |
| Type | JENKINS_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60059/](https://ci.nodejs.org/job/node-test-pull-request/69556/), [https://github.com/nodejs/node/pull/60136/](https://ci.nodejs.org/job/node-test-pull-request/69597/)) |
| Appeared | [test-ibm-ubi81_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/53067/console), [test-ibm-ubuntu2404_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_icu_x64/53067/console), [test-ibm-ubuntu2404_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_openssl30_x64/53067/console), [test-ibm-ubuntu2404_sharedlibs_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_openssl32_x64/53067/console), [test-ibm-ubuntu2404_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_openssl35_x64/53067/console), [test-ibm-ubuntu2404_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_shared_x64/53067/console), [vm-wpeon](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-arm64/67157/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69556/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69597/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubi81_sharedlibs_openssl111fips_x64/53067/console">Example</a></summary>

```
Build timed out (after 60 minutes). Marking the build as failed.
```
</details>

-------


### Git Failure


### Build Failure

| Reason | <code>ERROR: Step ‘Record fingerprints of files to track usage’ failed: no workspace for ...</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/60142/](https://ci.nodejs.org/job/node-test-pull-request/69594/), [https://github.com/nodejs/node/pull/60144/](https://ci.nodejs.org/job/node-test-pull-request/69595/), [https://github.com/nodejs/node/pull/60136/](https://ci.nodejs.org/job/node-test-pull-request/69601/)) |
| Appeared | [test-rackspace-debian12-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=debian12-x64/66903/console), [test-ibm-alpine322_container-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-latest-x64/66896/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69594/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69601/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=debian12-x64/66903/console">Example</a></summary>

```
ERROR: Step ‘Record fingerprints of files to track usage’ failed: no workspace for node-test-commit-linux/nodes=debian12-x64 #66903
Collecting metadata...
Metadata collection done.
[Checks API] No suitable checks publisher found.
Notifying upstream projects of job completion
Finished: FAILURE
```
</details>

-------

| Reason | <code>fatal error: ld terminated with signal 9 [Killed]</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60098/](https://ci.nodejs.org/job/node-test-pull-request/69596/), [https://github.com/nodejs/node/pull/60062/](https://ci.nodejs.org/job/node-test-pull-request/69646/)) |
| Appeared | [test-azure-ubuntu2204_container-arm64-6](https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/20653/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69596/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69646/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-arm-debug/nodes=ubuntu2204_debug-arm64/20653/console">Example</a></summary>

```
fatal error: ld terminated with signal 9 [Killed]
```
</details>

-------


### JSTest Failure

| Reason | <code>parallel/test-without-async-context-frame</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 19 ([https://github.com/nodejs/node/pull/59952/](https://ci.nodejs.org/job/node-test-pull-request/69553/), [https://github.com/nodejs/node/pull/60123/](https://ci.nodejs.org/job/node-test-pull-request/69569/), [https://github.com/nodejs/node/pull/60059/](https://ci.nodejs.org/job/node-test-pull-request/69570/), [https://github.com/nodejs/node/pull/60008/](https://ci.nodejs.org/job/node-test-pull-request/69577/), [https://github.com/nodejs/node/pull/60061/](https://ci.nodejs.org/job/node-test-pull-request/69593/), [https://github.com/nodejs/node/pull/60142/](https://ci.nodejs.org/job/node-test-pull-request/69594/), [https://github.com/nodejs/node/pull/60098/](https://ci.nodejs.org/job/node-test-pull-request/69596/), [https://github.com/nodejs/node/pull/59889/](https://ci.nodejs.org/job/node-test-pull-request/69603/), [https://github.com/nodejs/node/pull/60153/](https://ci.nodejs.org/job/node-test-pull-request/69606/), [https://github.com/nodejs/node/pull/60160/](https://ci.nodejs.org/job/node-test-pull-request/69617/), [https://github.com/nodejs/node/pull/59853/](https://ci.nodejs.org/job/node-test-pull-request/69618/), [https://github.com/nodejs/node/pull/59931/](https://ci.nodejs.org/job/node-test-pull-request/69619/), [https://github.com/nodejs/node/pull/60148/](https://ci.nodejs.org/job/node-test-pull-request/69623/), [https://github.com/nodejs/node/pull/60144/](https://ci.nodejs.org/job/node-test-pull-request/69624/), [https://github.com/nodejs/node/pull/60174/](https://ci.nodejs.org/job/node-test-pull-request/69637/), [https://github.com/nodejs/node/pull/60133/](https://ci.nodejs.org/job/node-test-pull-request/69639/), [https://github.com/nodejs/node/pull/60177/](https://ci.nodejs.org/job/node-test-pull-request/69642/), [https://github.com/nodejs/node/pull/60156/](https://ci.nodejs.org/job/node-test-pull-request/69645/), [https://github.com/nodejs/node/pull/60168/](https://ci.nodejs.org/job/node-test-pull-request/69647/)) |
| Appeared | [vm-0b80q](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67264/console), [test-ibm-ubuntu2404_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_shared_x64/53105/console), [vm-hw69r](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67258/console), [vm-s4ci3](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67255/console), [vm-nd723](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67253/console), [vm-6zndc](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67236/console), [vm-hgw3t](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67235/console), [vm-ebad9](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67231/console), [vm-dm937](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67230/console), [vm-x4kfi](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67229/console), [vm-532du](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67215/console), [vm-f8xgr](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67211/console), [test-digitalocean-ubuntu2404_sharedlibs_container-x64-9](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_shared_x64/53072/console), [test-digitalocean-ubuntu2404_sharedlibs_container-x64-3](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_shared_x64/53068/console), [test-digitalocean-ubuntu2404_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_shared_x64/53065/console), [vm-1z6qj](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67202/console), [test-ibm-ubuntu2404_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_shared_x64/53064/console), [vm-2on5c](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67201/console), [vm-mqg3w](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67181/console), [vm-tklkv](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67173/console), [vm-1i229](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67172/console), [vm-66gbr](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67154/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69553/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69647/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67264/console">Example</a></summary>

```
not ok 4216 parallel/test-without-async-context-frame
  ---
  duration_ms: 120106.88100
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>sequential/test-worker-prof</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 14 ([https://github.com/nodejs/node/pull/59968/](https://ci.nodejs.org/job/node-test-pull-request/69567/), [https://github.com/nodejs/node/pull/60125/](https://ci.nodejs.org/job/node-test-pull-request/69579/), [https://github.com/nodejs/node/pull/60142/](https://ci.nodejs.org/job/node-test-pull-request/69594/), [https://github.com/nodejs/node/pull/59889/](https://ci.nodejs.org/job/node-test-pull-request/69599/), [https://github.com/nodejs/node/pull/60153/](https://ci.nodejs.org/job/node-test-pull-request/69606/), [https://github.com/nodejs/node/pull/59853/](https://ci.nodejs.org/job/node-test-pull-request/69614/), [https://github.com/nodejs/node/pull/60148/](https://ci.nodejs.org/job/node-test-pull-request/69623/), [https://github.com/nodejs/node/pull/59873/](https://ci.nodejs.org/job/node-test-pull-request/69633/), [https://github.com/nodejs/node/pull/60098/](https://ci.nodejs.org/job/node-test-pull-request/69638/), [https://github.com/nodejs/node/pull/60133/](https://ci.nodejs.org/job/node-test-pull-request/69639/), [https://github.com/nodejs/node/pull/60177/](https://ci.nodejs.org/job/node-test-pull-request/69642/), [https://github.com/nodejs/node/pull/60168/](https://ci.nodejs.org/job/node-test-pull-request/69644/), [https://github.com/nodejs/node/pull/60156/](https://ci.nodejs.org/job/node-test-pull-request/69645/), [https://github.com/nodejs/node/pull/60061/](https://ci.nodejs.org/job/node-test-pull-request/69648/)) |
| Appeared | [test-azure_msft-win10_vs2019-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win10-COMPILED_BY-vs2022_clang/37193/console), [test-azure_msft-win10_vs2019-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win10-COMPILED_BY-vs2022_clang/37189/console), [test-azure_msft-win10_vs2019-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win10-COMPILED_BY-vs2022_clang/37188/console), [test-azure_msft-win11_vs2022-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-COMPILED_BY-vs2022_clang/37191/console), [test-ibm-rhel8-s390x-3](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/51901/console), [test-linuxonecc-rhel9-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel9-s390x/51898/console), [test-azure_msft-win11_vs2022-arm64-6](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/37173/console), [test-ibm-rhel8-s390x-1](https://ci.nodejs.org/job/node-test-commit-linuxone/nodes=rhel8-s390x/51877/console), [test-azure_msft-win11_vs2022-arm64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/37130/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69567/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69648/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win10-COMPILED_BY-vs2022_clang/37193/console">Example</a></summary>

```
not ok 1143 sequential/test-worker-prof
  ---
  duration_ms: 2510.25900
  severity: fail
  exitcode: 1
  stack: |-
    files found in working directory before worker starts [ 'isolate-0000017A7E018000-8016-v8.log' ]
    parent prof file: isolate-0000017A7E018000-8016-v8.log
    parent posted 36266 messages
    files found in working directory before worker exits [
      'isolate-0000017A18457000-8016-v8.log',
      'isolate-0000017A7E018000-8016-v8.log'
    ]
    worker prof file: isolate-0000017A18457000-8016-v8.log
    
    worker ticks 12
    parent ticks 32
    node:internal/assert/utils:77
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: worker ticks <= 15:
    tick,0x7ff657c36ddb,93521,0,0x0,3,0x7ff65623fcd0,0x17a58e4ed78,0x160f0499cbd,0x17a39042a4f,0x17a39042607,0x160f04938f3,0x160f048c4b1,0x160f048c337,0x160f0492679
    tick,0x7ff6562bff7a,109427,0,0x0,2,0x17a3904297e,0x17a39042607,0x160f049f0cd,0x17a39042a4f,0x17a39042607,0x160f049db70,0x160f04926dc
    tick,0x7ff6562d7f8a,141397...
```
</details>

-------

| Reason | <code>sequential/test-perf-hooks</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 12 ([https://github.com/nodejs/node/pull/60059/](https://ci.nodejs.org/job/node-test-pull-request/69556/), [https://github.com/nodejs/node/pull/60144/](https://ci.nodejs.org/job/node-test-pull-request/69595/), [https://github.com/nodejs/node/pull/60153/](https://ci.nodejs.org/job/node-test-pull-request/69606/), [https://github.com/nodejs/node/pull/60174/](https://ci.nodejs.org/job/node-test-pull-request/69637/), [https://github.com/nodejs/node/pull/60098/](https://ci.nodejs.org/job/node-test-pull-request/69638/), [https://github.com/nodejs/node/pull/60133/](https://ci.nodejs.org/job/node-test-pull-request/69639/), [https://github.com/nodejs/node/pull/60131/](https://ci.nodejs.org/job/node-test-pull-request/69640/), [https://github.com/nodejs/node/pull/60177/](https://ci.nodejs.org/job/node-test-pull-request/69642/), [https://github.com/nodejs/node/pull/60156/](https://ci.nodejs.org/job/node-test-pull-request/69645/), [https://github.com/nodejs/node/pull/60168/](https://ci.nodejs.org/job/node-test-pull-request/69647/), [https://github.com/nodejs/node/pull/59807/](https://ci.nodejs.org/job/node-test-pull-request/69649/), [https://github.com/nodejs/node/pull/60061/](https://ci.nodejs.org/job/node-test-pull-request/69650/)) |
| Appeared | [vm-xc3hr](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67252/console), [vm-nd723](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67265/console), [test-digitalocean-ubuntu2404_sharedlibs_container-x64-9](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_openssl31_x64/53105/console), [vm-s4ci3](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67255/console), [vm-532du](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67215/console), [test-digitalocean-ubuntu2404_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_openssl30_x64/53065/console), [vm-zqytd](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67183/console), [vm-66gbr](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67157/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69556/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69650/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67252/console">Example</a></summary>

```
not ok 4226 sequential/test-perf-hooks
  ---
  duration_ms: 669.75600
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/assert/utils:281
        throw err;
        ^
    
    AssertionError [ERR_ASSERTION]: Date.now() - performance.timeOrigin (344.26708984375) - process.uptime() * 1000 (272.466882) = 71.80020784375 >= +- 50
        at Object.<anonymous> (/Users/admin/build/workspace/node-test-commit-osx/nodes/osx13-x64/test/sequential/test-perf-hooks.js:35:3)
        at Module._compile (node:internal/modules/cjs/loader:1521:14)
        at Module._extensions..js (node:internal/modules/cjs/loader:1623:10)
        at Module.load (node:internal/modules/cjs/loader:1266:32)
        at Module._load (node:internal/modules/cjs/loader:1091:12)
        at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:164:12)
        at node:internal/main/run_main_module:28:49 {
      generatedMessage: false,
      code: 'ERR_ASSERTION',
      actual: false,
      expected: true,
      operator: '...
```
</details>

-------

| Reason | <code>client-proxy/test-https-proxy-request-invalid-char-in-url</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 8 ([https://github.com/nodejs/node/pull/60060/](https://ci.nodejs.org/job/node-test-pull-request/69554/), [https://github.com/nodejs/node/pull/60123/](https://ci.nodejs.org/job/node-test-pull-request/69569/), [https://github.com/nodejs/node/pull/59889/](https://ci.nodejs.org/job/node-test-pull-request/69599/), [https://github.com/nodejs/node/pull/59432/](https://ci.nodejs.org/job/node-test-pull-request/69612/), [https://github.com/nodejs/node/pull/59853/](https://ci.nodejs.org/job/node-test-pull-request/69618/), [https://github.com/nodejs/node/pull/60098/](https://ci.nodejs.org/job/node-test-pull-request/69638/), [https://github.com/nodejs/node/pull/60061/](https://ci.nodejs.org/job/node-test-pull-request/69648/), [https://github.com/nodejs/node/pull/59807/](https://ci.nodejs.org/job/node-test-pull-request/69649/)) |
| Appeared | [vm-n9jtk](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67266/console), [vm-nd723](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67265/console), [vm-kxsdk](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67254/console), [vm-dm937](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67230/console), [vm-qghf4](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67223/console), [vm-532du](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67207/console), [vm-1i229](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67172/console), [vm-qe5tw](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67155/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69554/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69649/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67266/console">Example</a></summary>

```
not ok 4376 client-proxy/test-https-proxy-request-invalid-char-in-url
  ---
  duration_ms: 761.56900
  severity: fail
  exitcode: 1
  stack: |-
    [Upstream server] responding to request for '/newline-in-host'
    [Upstream server] responding to request for '/carriage-return-in-host'
    [Upstream server] responding to request for '/crlf-in-host'
    [Proxy client] Received response from server for 'https://local\nhost:55432/newline-in-host': Response for '/newline-in-host'
    [Proxy client] #1 closed request for: 'https://local\nhost:55432/newline-in-host'
    [Proxy client] Received response from server for 'https://local\rhost:55432/carriage-return-in-host': Response for '/carriage-return-in-host'
    [Proxy client] #2 closed request for: 'https://local\rhost:55432/carriage-return-in-host'
    [Proxy client] Received response from server for 'https://local\r\nhost:55432/crlf-in-host': Response for '/crlf-in-host'
    [Proxy client] #3 closed request for: 'https://local\r\nhost:55432/crlf-in-host'
    [Up...
```
</details>

-------

| Reason | <code>parallel/test-http2-close-while-writing</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 8 ([https://github.com/nodejs/node/pull/60174/](https://ci.nodejs.org/job/node-test-pull-request/69637/), [https://github.com/nodejs/node/pull/60098/](https://ci.nodejs.org/job/node-test-pull-request/69638/), [https://github.com/nodejs/node/pull/60133/](https://ci.nodejs.org/job/node-test-pull-request/69639/), [https://github.com/nodejs/node/pull/60131/](https://ci.nodejs.org/job/node-test-pull-request/69640/), [https://github.com/nodejs/node/pull/60177/](https://ci.nodejs.org/job/node-test-pull-request/69642/), [https://github.com/nodejs/node/pull/60168/](https://ci.nodejs.org/job/node-test-pull-request/69647/), [https://github.com/nodejs/node/pull/59807/](https://ci.nodejs.org/job/node-test-pull-request/69649/), [https://github.com/nodejs/node/pull/60061/](https://ci.nodejs.org/job/node-test-pull-request/69650/)) |
| Appeared | [vm-xc3hr](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67252/console), [vm-n9jtk](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67266/console), [vm-nd723](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67265/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69637/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69650/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67252/console">Example</a></summary>

```
not ok 2451 parallel/test-http2-close-while-writing
  ---
  duration_ms: 120135.97200
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-runner-run-watch</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 6 ([https://github.com/nodejs/node/pull/60060/](https://ci.nodejs.org/job/node-test-pull-request/69554/), [https://github.com/nodejs/node/pull/60059/](https://ci.nodejs.org/job/node-test-pull-request/69556/), [https://github.com/nodejs/node/pull/59952/](https://ci.nodejs.org/job/node-test-pull-request/69558/), [https://github.com/nodejs/node/pull/60061/](https://ci.nodejs.org/job/node-test-pull-request/69563/), [https://github.com/nodejs/node/pull/60123/](https://ci.nodejs.org/job/node-test-pull-request/69569/), [https://github.com/nodejs/node/pull/60064/](https://ci.nodejs.org/job/node-test-pull-request/69571/)) |
| Appeared | [vm-jyntm](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67174/console), [vm-1i229](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67172/console), [vm-3jyui](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67164/console), [vm-qe5tw](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67159/console), [vm-66gbr](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67157/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69554/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69571/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67174/console">Example</a></summary>

```
not ok 2802 parallel/test-runner-run-watch
  ---
  duration_ms: 27535.14200
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: 'should run with different cwd while in watch mode and isolation "none"'
    Location: test/parallel/test-runner-run-watch.mjs:358:5
    AssertionError [ERR_ASSERTION]: function should not have been called at file:///Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/test/parallel/test-runner-run-watch.mjs:373
    called with arguments: [Object: null prototype] {
      name: '<anonymous>',
      nesting: 0,
      testNumber: 1,
      details: [Object: null prototype] {
        duration_ms: 210.990362,
        type: 'test',
        error: [Error: test failed] {
          code: 'ERR_TEST_FAILURE',
          failureType: 'testCodeFailure',
          cause: 'test failed',
          exitCode: null,
          signal: 'SIGTERM'
        }
      },
      line: 1,
      column: 1,
      file: '/Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/<anonymo...
```
</details>

-------

| Reason | <code>wpt/test-hr-time</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 6 ([https://github.com/nodejs/node/pull/60009/](https://ci.nodejs.org/job/node-test-pull-request/69573/), [https://github.com/nodejs/node/pull/60160/](https://ci.nodejs.org/job/node-test-pull-request/69617/), [https://github.com/nodejs/node/pull/59853/](https://ci.nodejs.org/job/node-test-pull-request/69618/), [https://github.com/nodejs/node/pull/60174/](https://ci.nodejs.org/job/node-test-pull-request/69637/), [https://github.com/nodejs/node/pull/60131/](https://ci.nodejs.org/job/node-test-pull-request/69640/), [https://github.com/nodejs/node/pull/60061/](https://ci.nodejs.org/job/node-test-pull-request/69650/)) |
| Appeared | [vm-n9jtk](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67267/console), [vm-nd723](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67256/console), [vm-dm937](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67230/console), [vm-x4kfi](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67229/console), [vm-2on5c](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67201/console), [vm-2zf9u](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67176/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69573/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69650/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67267/console">Example</a></summary>

```
not ok 4821 wpt/test-hr-time
  ---
  duration_ms: 2399.56500
  severity: fail
  exitcode: 1
  stack: |-
    [SKIPPED] idlharness-shadowrealm.window.js: ShadowRealm support is not enabled
    [SKIPPED] window-worker-timeOrigin.window.js: depends on URL.createObjectURL(blob)
    [PASS] self.performance.now() is a function that returns a number
    [PASS] self.performance.now() returns a positive number
    [PASS] self.performance.now() difference is not negative
    [PASS] Performance interface extends EventTarget.
    [PASS] self.performance.now() returns a positive number
    [PASS] self.performance.now() difference is not negative
    [PASS] idl_test validation
    [PASS] Partial interface mixin WindowOrWorkerGlobalScope: original interface mixin defined
    [PASS] Partial interface mixin WindowOrWorkerGlobalScope: member names are unique
    [PASS] Partial interface Window: member names are unique
    [PASS] Window includes GlobalEventHandlers: member names are unique
    [PASS] Window includes WindowEventH...
```
</details>

-------

| Reason | <code>parallel/test-runner-watch-mode-kill-signal</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/60123/](https://ci.nodejs.org/job/node-test-pull-request/69564/), [https://github.com/nodejs/node/pull/60132/](https://ci.nodejs.org/job/node-test-pull-request/69584/), [https://github.com/nodejs/node/pull/59432/](https://ci.nodejs.org/job/node-test-pull-request/69611/), [https://github.com/nodejs/node/pull/60148/](https://ci.nodejs.org/job/node-test-pull-request/69615/), [https://github.com/nodejs/node/pull/59807/](https://ci.nodejs.org/job/node-test-pull-request/69649/)) |
| Appeared | [vm-n9jtk](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67266/console), [vm-ebad9](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67227/console), [vm-htd7e](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-arm64/67222/console), [vm-zav92](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67190/console), [test-azure-ubuntu2204_container-arm64-5](https://ci.nodejs.org/job/node-test-commit-arm/nodes=ubuntu2204-arm64/60617/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69564/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69649/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67266/console">Example</a></summary>

```
not ok 3422 parallel/test-runner-watch-mode-kill-signal
  ---
  duration_ms: 120076.91900
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-quic-test-client</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/59952/](https://ci.nodejs.org/job/node-test-pull-request/69560/), [https://github.com/nodejs/node/pull/60168/](https://ci.nodejs.org/job/node-test-pull-request/69628/), [https://github.com/nodejs/node/pull/60174/](https://ci.nodejs.org/job/node-test-pull-request/69635/), [https://github.com/nodejs/node/pull/60061/](https://ci.nodejs.org/job/node-test-pull-request/69650/)) |
| Appeared | [vm-n9jtk](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67267/console), [vm-ibfq1](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67250/console), [vm-nvuji](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67240/console), [vm-m34hc](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67161/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69560/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69650/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67267/console">Example</a></summary>

```
not ok 2581 parallel/test-quic-test-client
  ---
  duration_ms: 2553.39500
  severity: fail
  exitcode: 1
  stack: |-
    /Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/out/Release/ngtcp2_test_client
    node:internal/modules/run_main:107
        triggerUncaughtException(
        ^
    
    AssertionError [ERR_ASSERTION]: Missing expected rejection.
        at process.processTicksAndRejections (node:internal/process/task_queues:103:5)
        at async file:///Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/test/parallel/test-quic-test-client.mjs:31:1 {
      generatedMessage: false,
      code: 'ERR_ASSERTION',
      actual: undefined,
      expected: { message: /Process exited with code 1 and signal null/ },
      operator: 'rejects',
      diff: 'simple'
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-fs-watch-recursive-delete</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60142/](https://ci.nodejs.org/job/node-test-pull-request/69594/), [https://github.com/nodejs/node/pull/60144/](https://ci.nodejs.org/job/node-test-pull-request/69595/)) |
| Appeared | [test-digitalocean-fedora41-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=fedora-last-latest-x64/66896/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69594/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69595/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=fedora-last-latest-x64/66896/console">Example</a></summary>

```
not ok 1493 parallel/test-fs-watch-recursive-delete
  ---
  duration_ms: 707.52200
  severity: fail
  exitcode: 1
  stack: |-
    node:events:486
          throw er; // Unhandled 'error' event
          ^
    
    Error: ENOENT: no such file or directory, scandir '/home/iojs/node-tmp/.tmp.1492/parent/child'
        at readdirSync (node:fs:1545:26)
        at #watchFolder (node:internal/fs/recursive_watch:111:21)
        at FSWatcher.<anonymous> (node:internal/fs/recursive_watch:191:26)
        at FSWatcher.emit (node:events:508:28)
        at FSWatcher._handle.onchange (node:internal/fs/watchers:222:12)
    Emitted 'error' event on FSWatcher instance at:
        at #watchFolder (node:internal/fs/recursive_watch:143:12)
        at FSWatcher.<anonymous> (node:internal/fs/recursive_watch:191:26)
        at FSWatcher.emit (node:events:508:28)
        at FSWatcher._handle.onchange (node:internal/fs/watchers:222:12) {
      errno: -2,
      code: 'ENOENT',
      syscall: 'scandir',
      path: '/home/iojs/node-tmp/...
```
</details>

-------

| Reason | <code>parallel/test-zlib-brotli-16GB</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60153/](https://ci.nodejs.org/job/node-test-pull-request/69606/), [https://github.com/nodejs/node/pull/60148/](https://ci.nodejs.org/job/node-test-pull-request/69615/)) |
| Appeared | [vm-ebad9](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67227/console), [vm-532du](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67215/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69606/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69615/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67227/console">Example</a></summary>

```
not ok 3857 parallel/test-zlib-brotli-16GB
  ---
  duration_ms: 1422.15600
  severity: fail
  exitcode: 1
  stack: |-
    node:assert:149
      throw new AssertionError(obj);
      ^
    
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    
    0 !== 4
    
        at Timeout.<anonymous> (/Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/test/parallel/test-zlib-brotli-16GB.js:22:3)
        at Timeout._onTimeout (/Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/test/common/index.js:475:15)
        at listOnTimeout (node:internal/timers:605:17)
        at process.processTimers (node:internal/timers:541:7) {
      generatedMessage: true,
      code: 'ERR_ASSERTION',
      actual: 0,
      expected: 4,
      operator: 'strictEqual',
      diff: 'simple'
    }
    
    Node.js v25.0.0-pre
  ...

```
</details>

-------

| Reason | <code>wpt/test-wasm-webapi</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60148/](https://ci.nodejs.org/job/node-test-pull-request/69615/), [https://github.com/nodejs/node/pull/60177/](https://ci.nodejs.org/job/node-test-pull-request/69642/)) |
| Appeared | [test-azure_msft-win11_vs2022-arm64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/37191/console), [test-azure_msft-win11_vs2022-arm64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/37164/console), [test-azure_msft-win11_vs2022-arm64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/37156/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69615/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69642/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/37191/console">Example</a></summary>

```
not ok 1148 wpt/test-wasm-webapi
  ---
  duration_ms: 432.68200
  severity: crashed
  exitcode: 3221225477
  stack: |-
    [SKIPPED] abort.any.js: WPTRunner does not support fetch()
    [SKIPPED] contenttype.any.js: WPTRunner does not support fetch()
    [SKIPPED] historical.any.js: indexedDB is not defined
    [SKIPPED] idlharness.any.js: not configured
    [SKIPPED] instantiateStreaming-bad-imports.any.js: Flaky on ARM with V8 >= 11.2
    [SKIPPED] origin.sub.any.js: CORS not implemented
    [SKIPPED] status.any.js: WPTRunner does not support fetch()
    [PASS] compileStreaming
    [PASS] instantiateStreaming
    [PASS] compileStreaming: no body
    [PASS] compileStreaming: no body in a promise
    [PASS] compileStreaming: undefined
    [PASS] compileStreaming: undefined in a promise
    [PASS] compileStreaming: null
    [PASS] compileStreaming: null in a promise
    [PASS] compileStreaming: true
    [PASS] compileStreaming: true in a promise
    [PASS] compileStreaming: "test"
    [PASS] compileStreaming: ...
```
</details>

-------

