Failures in [node-test-pull-request/69738](https://ci.nodejs.org/job/node-test-pull-request/69738/) to [node-test-pull-request/69836](https://ci.nodejs.org/job/node-test-pull-request/69836/) that failed 2 or more PRs
(Generated with `ncu-ci walk pr --stats=true --markdown reports/2025-10-21.md`)

| UTC Time         | RUNNING | SUCCESS | UNSTABLE | ABORTED | FAILURE | Green Rate |
| ---------------- | ------- | ------- | -------- | ------- | ------- | ---------- |
| 2025-10-21 00:11 | 1       | 15      | 17       | 3       | 64      | 15.63%     |


### Jenkins Failure


### JSTest Failure

| Reason | <code>parallel/test-without-async-context-frame</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 13 ([https://github.com/nodejs/node/pull/60250/](https://ci.nodejs.org/job/node-test-pull-request/69746/), [https://github.com/nodejs/node/pull/60254/](https://ci.nodejs.org/job/node-test-pull-request/69763/), [https://github.com/nodejs/node/pull/60256/](https://ci.nodejs.org/job/node-test-pull-request/69764/), [https://github.com/nodejs/node/pull/60244/](https://ci.nodejs.org/job/node-test-pull-request/69765/), [https://github.com/nodejs/node/pull/60217/](https://ci.nodejs.org/job/node-test-pull-request/69766/), [https://github.com/nodejs/node/pull/60278/](https://ci.nodejs.org/job/node-test-pull-request/69773/), [https://github.com/nodejs/node/pull/60205/](https://ci.nodejs.org/job/node-test-pull-request/69778/), [https://github.com/nodejs/node/pull/60266/](https://ci.nodejs.org/job/node-test-pull-request/69780/), [https://github.com/nodejs/node/pull/60271/](https://ci.nodejs.org/job/node-test-pull-request/69781/), [https://github.com/nodejs/node/pull/60277/](https://ci.nodejs.org/job/node-test-pull-request/69785/), [https://github.com/nodejs/node/pull/60272/](https://ci.nodejs.org/job/node-test-pull-request/69786/), [https://github.com/nodejs/node/pull/60269/](https://ci.nodejs.org/job/node-test-pull-request/69793/), [https://github.com/nodejs/node/pull/60289/](https://ci.nodejs.org/job/node-test-pull-request/69799/)) |
| Appeared | [vm-xrtit](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67444/console), [vm-qeafq](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67435/console), [vm-4tv35](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67433/console), [vm-oa16m](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67427/console), [vm-bmoqy](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67419/console), [test-digitalocean-ubuntu2404_sharedlibs_container-x64-6](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_shared_x64/53203/console), [test-digitalocean-ubuntu2404_sharedlibs_container-x64-8](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_shared_x64/53197/console), [vm-gy321](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67409/console), [vm-imm7g](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67408/console), [test-digitalocean-ubuntu2404_sharedlibs_container-x64-9](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_shared_x64/53195/console), [vm-gnhs2](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67406/console), [test-digitalocean-ubuntu2404_sharedlibs_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_shared_x64/53193/console), [vm-oiqpl](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67401/console), [vm-263lv](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67399/console), [vm-iv9zi](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67388/console), [vm-tn28e](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67387/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69746/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69799/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67444/console">Example</a></summary>

```
not ok 4167 parallel/test-without-async-context-frame
  ---
  duration_ms: 120040.46100
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>sequential/test-worker-prof</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 10 ([https://github.com/nodejs/node/pull/60250/](https://ci.nodejs.org/job/node-test-pull-request/69750/), [https://github.com/nodejs/node/pull/59873/](https://ci.nodejs.org/job/node-test-pull-request/69752/), [https://github.com/nodejs/node/pull/60276/](https://ci.nodejs.org/job/node-test-pull-request/69759/), [https://github.com/nodejs/node/pull/60244/](https://ci.nodejs.org/job/node-test-pull-request/69765/), [https://github.com/nodejs/node/pull/60217/](https://ci.nodejs.org/job/node-test-pull-request/69766/), [https://github.com/nodejs/node/pull/60254/](https://ci.nodejs.org/job/node-test-pull-request/69770/), [https://github.com/nodejs/node/pull/60269/](https://ci.nodejs.org/job/node-test-pull-request/69779/), [https://github.com/nodejs/node/pull/60266/](https://ci.nodejs.org/job/node-test-pull-request/69796/), [https://github.com/nodejs/node/pull/60289/](https://ci.nodejs.org/job/node-test-pull-request/69814/), [https://github.com/nodejs/node/pull/60274/](https://ci.nodejs.org/job/node-test-pull-request/69818/)) |
| Appeared | [test-azure_msft-win10_vs2019-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win10-COMPILED_BY-vs2022_clang/37337/console), [test-azure_msft-win10_vs2019-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win10-COMPILED_BY-vs2022_clang/37332/console), [test-azure_msft-win10_vs2019-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win10-COMPILED_BY-vs2022_clang/37326/console), [test-azure_msft-win11_vs2022-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2022_clang/37322/console), [test-azure_msft-win11_vs2022-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-COMPILED_BY-vs2022_clang/37304/console), [test-azure_msft-win11_vs2022-arm64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/37291/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69750/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69818/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win10-COMPILED_BY-vs2022_clang/37337/console">Example</a></summary>

```
not ok 1146 sequential/test-worker-prof
  ---
  duration_ms: 2408.23400
  severity: fail
  exitcode: 1
  stack: |-
    files found in working directory before worker starts [ 'isolate-0000024F1AE02000-6792-v8.log' ]
    parent prof file: isolate-0000024F1AE02000-6792-v8.log
    parent posted 47590 messages
    files found in working directory before worker exits [
      'isolate-0000024F1AE02000-6792-v8.log',
      'isolate-0000024F3436F000-6792-v8.log'
    ]
    worker prof file: isolate-0000024F3436F000-6792-v8.log
    
    worker ticks 9
    parent ticks 36
    node:internal/assert/utils:146
      throw error;
      ^
    
    AssertionError [ERR_ASSERTION]: worker ticks <= 10:
    tick,0x7ff7526bd394,34961,0,0x0,0,0x7ff752ae5c50,0x24f54f40fa2,0x15545dc9971,0x24f74d957e7,0x15545dc6684
    tick,0x7ff7525a7d60,50952,0,0x0,0,0x7ff752551550,0x24f74e06fcf,0x15545dd1e75,0x15545dd1b7b,0x15545dd1822,0x15545dcf075,0x15545dcca31,0x15545dcc8b7,0x15545dcc745,0x15545dcbfe4
    tick,0x7ff7526e8033,67085,0,0x0,0,0x7ff752...
```
</details>

-------

| Reason | <code>parallel/test-quic-test-client</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 7 ([https://github.com/nodejs/node/pull/60245/](https://ci.nodejs.org/job/node-test-pull-request/69748/), [https://github.com/nodejs/node/pull/60250/](https://ci.nodejs.org/job/node-test-pull-request/69750/), [https://github.com/nodejs/node/pull/60272/](https://ci.nodejs.org/job/node-test-pull-request/69755/), [https://github.com/nodejs/node/pull/60266/](https://ci.nodejs.org/job/node-test-pull-request/69757/), [https://github.com/nodejs/node/pull/60217/](https://ci.nodejs.org/job/node-test-pull-request/69766/), [https://github.com/nodejs/node/pull/60277/](https://ci.nodejs.org/job/node-test-pull-request/69785/), [https://github.com/nodejs/node/pull/60178/](https://ci.nodejs.org/job/node-test-pull-request/69808/)) |
| Appeared | [vm-92kcy](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67452/console), [vm-qeafq](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67432/console), [test-mnx-smartos23-x64-6](https://ci.nodejs.org/job/node-test-commit-smartos/nodes=smartos23-x64/62847/console), [vm-oiqpl](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67401/console), [vm-263lv](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67399/console), [vm-jovkh](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67391/console), [vm-j9sr5](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67389/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69748/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69808/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67452/console">Example</a></summary>

```
not ok 2573 parallel/test-quic-test-client
  ---
  duration_ms: 1435.47400
  severity: fail
  exitcode: 1
  stack: |-
    /Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/out/Release/ngtcp2_test_client
    node:internal/modules/run_main:107
        triggerUncaughtException(
        ^
    
    AssertionError [ERR_ASSERTION]: Missing expected rejection.
        at process.processTicksAndRejections (node:internal/process/task_queues:103:5)
        at async file:///Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/test/parallel/test-quic-test-client.mjs:36:1 {
      generatedMessage: false,
      code: 'ERR_ASSERTION',
      actual: undefined,
      expected: { message: /Process exited with code 1 and signal null/ },
      operator: 'rejects',
      diff: 'simple'
    }
    
    Node.js v26.0.0-pre
  ...

```
</details>

-------

| Reason | <code>parallel/test-runner-output</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 7 ([https://github.com/nodejs/node/pull/60245/](https://ci.nodejs.org/job/node-test-pull-request/69741/), [https://github.com/nodejs/node/pull/60205/](https://ci.nodejs.org/job/node-test-pull-request/69762/), [https://github.com/nodejs/node/pull/60271/](https://ci.nodejs.org/job/node-test-pull-request/69775/), [https://github.com/nodejs/node/pull/60131/](https://ci.nodejs.org/job/node-test-pull-request/69792/), [https://github.com/nodejs/node/pull/60266/](https://ci.nodejs.org/job/node-test-pull-request/69796/), [https://github.com/nodejs/node/pull/60274/](https://ci.nodejs.org/job/node-test-pull-request/69818/), [https://github.com/nodejs/node/pull/59873/](https://ci.nodejs.org/job/node-test-pull-request/69835/)) |
| Appeared | [vm-zn9if](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67483/console), [undefined](https://ci.nodejs.org/job/node-test-commit-custom-suites-freestyle/44458/console), [test-azure_msft-win11_vs2022-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-COMPILED_BY-vs2022_clang/37319/console), [test-osuosl-aix72-ppc64_be-4](https://ci.nodejs.org/job/node-test-commit-aix/nodes=aix72-ppc64/59443/console), [vm-oa16m](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67421/console), [vm-gnhs2](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67406/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69741/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69835/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67483/console">Example</a></summary>

```
not ok 2761 parallel/test-runner-output
  ---
  duration_ms: 7082.50300
  severity: fail
  exitcode: 1
  stack: |-
    Test failure: 'test-runner/output/test-timeout-flag.js'
    Location: test/parallel/test-runner-output.mjs:356:5
    AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
    + actual - expected
    ... Skipped lines
    
      'TAP version 13\n' +
        '# Subtest: --test-timeout is set to 100ms\n' +
        '    # Subtest: should timeout after 100ms\n' +
        '    not ok 1 - should timeout after 100ms\n' +
        '      ---\n' +
    ...

```
</details>

-------

| Reason | <code>parallel/test-runner-watch-mode-kill-signal</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/60244/](https://ci.nodejs.org/job/node-test-pull-request/69765/), [https://github.com/nodejs/node/pull/60178/](https://ci.nodejs.org/job/node-test-pull-request/69777/), [https://github.com/nodejs/node/pull/60271/](https://ci.nodejs.org/job/node-test-pull-request/69789/), [https://github.com/nodejs/node/pull/60205/](https://ci.nodejs.org/job/node-test-pull-request/69790/), [https://github.com/nodejs/node/pull/60274/](https://ci.nodejs.org/job/node-test-pull-request/69818/)) |
| Appeared | [vm-e3hoc](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-arm64/67463/console), [vm-4tv35](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67437/console), [vm-oa16m](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67436/console), [vm-bmoqy](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67424/console), [vm-qeafq](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67418/console), [vm-gy321](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67409/console), [vm-gnhs2](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67406/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69765/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69818/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-arm64/67463/console">Example</a></summary>

```
not ok 4776 parallel/test-runner-watch-mode-kill-signal
  ---
  duration_ms: 360060.83100
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-http2-close-while-writing</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/60269/](https://ci.nodejs.org/job/node-test-pull-request/69779/), [https://github.com/nodejs/node/pull/60271/](https://ci.nodejs.org/job/node-test-pull-request/69794/), [https://github.com/nodejs/node/pull/60289/](https://ci.nodejs.org/job/node-test-pull-request/69799/), [https://github.com/nodejs/node/pull/60278/](https://ci.nodejs.org/job/node-test-pull-request/69823/)) |
| Appeared | [vm-o2tby](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67468/console), [vm-xrtit](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67444/console), [vm-ehfzr](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67441/console), [vm-qeafq](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67426/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69779/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69823/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67468/console">Example</a></summary>

```
not ok 2661 parallel/test-http2-close-while-writing
  ---
  duration_ms: 120078.47200
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>sequential/test-perf-hooks</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 4 ([https://github.com/nodejs/node/pull/60245/](https://ci.nodejs.org/job/node-test-pull-request/69744/), [https://github.com/nodejs/node/pull/60205/](https://ci.nodejs.org/job/node-test-pull-request/69762/), [https://github.com/nodejs/node/pull/60269/](https://ci.nodejs.org/job/node-test-pull-request/69788/), [https://github.com/nodejs/node/pull/60289/](https://ci.nodejs.org/job/node-test-pull-request/69799/)) |
| Appeared | [vm-xrtit](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67444/console), [vm-qeafq](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67435/console), [vm-gnhs2](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67406/console), [vm-l4ydv](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67400/console), [vm-iv9zi](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67385/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69744/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69799/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67444/console">Example</a></summary>

```
not ok 4765 sequential/test-perf-hooks
  ---
  duration_ms: 817.95400
  severity: fail
  exitcode: 1
  stack: |-
    node:internal/assert/utils:146
      throw error;
      ^
    
    AssertionError [ERR_ASSERTION]: Date.now() - performance.timeOrigin (417.280029296875) - process.uptime() * 1000 (289.587266) = 127.692763296875 >= +- 50
        at Object.<anonymous> (/Users/admin/build/workspace/node-test-commit-osx/nodes/macos15-x64/test/sequential/test-perf-hooks.js:36:3)
        at Module._compile (node:internal/modules/cjs/loader:1760:14)
        at Object..js (node:internal/modules/cjs/loader:1892:10)
        at Module.load (node:internal/modules/cjs/loader:1480:32)
        at Module._load (node:internal/modules/cjs/loader:1299:12)
        at TracingChannel.traceSync (node:diagnostics_channel:328:14)
        at wrapModuleLoad (node:internal/modules/cjs/loader:245:24)
        at Module.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:154:5)
        at node:internal/main/run_main_module:33...
```
</details>

-------

| Reason | <code>client-proxy/test-https-proxy-request-invalid-char-in-url</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 3 ([https://github.com/nodejs/node/pull/60250/](https://ci.nodejs.org/job/node-test-pull-request/69738/), [https://github.com/nodejs/node/pull/60178/](https://ci.nodejs.org/job/node-test-pull-request/69777/), [https://github.com/nodejs/node/pull/60266/](https://ci.nodejs.org/job/node-test-pull-request/69780/)) |
| Appeared | [vm-oa16m](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67427/console), [vm-bmoqy](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67424/console), [vm-cmeeo](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67379/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69738/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69780/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67427/console">Example</a></summary>

```
not ok 4378 client-proxy/test-https-proxy-request-invalid-char-in-url
  ---
  duration_ms: 533.88300
  severity: fail
  exitcode: 1
  stack: |-
    [Upstream server] responding to request for '/newline-in-host'
    [Upstream server] responding to request for '/carriage-return-in-host'
    [Upstream server] responding to request for '/carriage-return-in-port'
    [Upstream server] responding to request for '/crlf-in-host'
    [Proxy client] Received response from server for 'https://local\nhost:61468/newline-in-host': Response for '/newline-in-host'
    [Proxy client] #1 closed request for: 'https://local\nhost:61468/newline-in-host'
    [Proxy client] Received response from server for 'https://local\rhost:61468/carriage-return-in-host': Response for '/carriage-return-in-host'
    [Proxy client] #2 closed request for: 'https://local\rhost:61468/carriage-return-in-host'
    [Upstream server] responding to request for '/newline-in-port'
    [Proxy client] Received response from server for 'https://localhost:6\r1...
```
</details>

-------

| Reason | <code>parallel/test-fastutf8stream-periodicflush</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60245/](https://ci.nodejs.org/job/node-test-pull-request/69741/), [https://github.com/nodejs/node/pull/60326/](https://ci.nodejs.org/job/node-test-pull-request/69830/)) |
| Appeared | [test-ibm-rhel9-x64-1](https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel9-x64/67055/console), [test-digitalocean-alpine321_container-x64-2](https://ci.nodejs.org/job/node-test-commit-linux/nodes=alpine-last-latest-x64/66998/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69741/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69830/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-linux/nodes=rhel9-x64/67055/console">Example</a></summary>

```
not ok 1378 parallel/test-fastutf8stream-periodicflush
  ---
  duration_ms: 115.71500
  severity: fail
  exitcode: 1
  stack: |-
    node:assert:818
        throw newErr;
        ^
    
    AssertionError [ERR_ASSERTION]: ifError got unwanted exception: EBADF: bad file descriptor, write
        at /home/iojs/build/workspace/node/test/common/index.js:439:12
        at /home/iojs/build/workspace/node/test/common/index.js:476:15
        at Utf8Stream.onError (node:internal/streams/fast-utf8-stream:741:7)
        at Object.onceWrapper (node:events:623:26)
        at Utf8Stream.emit (node:events:508:28)
        at #release (node:internal/streams/fast-utf8-stream:413:14)
        at node:internal/streams/fast-utf8-stream:628:84
        at FSReqCallback.wrapper [as oncomplete] (node:fs:808:5) {
      generatedMessage: false,
      code: 'ERR_ASSERTION',
      actual: [Error: EBADF: bad file descriptor, write] {
        errno: -9,
        code: 'EBADF',
        syscall: 'write'
      },
      expected: null,
      ope...
```
</details>

-------

| Reason | <code>parallel/test-runner-watch-mode</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60139/](https://ci.nodejs.org/job/node-test-pull-request/69832/), [https://github.com/nodejs/node/pull/59873/](https://ci.nodejs.org/job/node-test-pull-request/69835/)) |
| Appeared | [vm-gthqd](https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67476/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69832/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69835/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=osx13-x64/67476/console">Example</a></summary>

```
not ok 2512 parallel/test-runner-watch-mode
  ---
  duration_ms: 12314.16600
  severity: fail
  exitcode: 1
  stack: |-
    TAP version 13
    # Subtest: test runner watch mode
        # Subtest: should run tests repeatedly
        ok 1 - should run tests repeatedly
          ---
          duration_ms: 2034.797083
          ...

```
</details>

-------

| Reason | <code>parallel/test-watch-mode-kill-signal-default</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60298/](https://ci.nodejs.org/job/node-test-pull-request/69810/), [https://github.com/nodejs/node/pull/59734/](https://ci.nodejs.org/job/node-test-pull-request/69825/)) |
| Appeared | [vm-v9dgt](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67470/console), [test-azure_msft-win10_vs2019-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win10-COMPILED_BY-vs2022_clang/37328/console), [test-azure_msft-win11_vs2022-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win11-COMPILED_BY-vs2022_clang/37328/console), [test-rackspace-win2019_vs2019-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2019-COMPILED_BY-vs2022_clang/37328/console), [test-rackspace-win2022_vs2022-x64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=2,nodes=win2022-COMPILED_BY-vs2022_clang/37328/console), [test-azure_msft-win11_vs2022-arm64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=3,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/37328/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69810/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69825/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67470/console">Example</a></summary>

```
not ok 4401 parallel/test-watch-mode-kill-signal-default
  ---
  duration_ms: 120075.80100
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>parallel/test-watch-mode-kill-signal-override</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60298/](https://ci.nodejs.org/job/node-test-pull-request/69810/), [https://github.com/nodejs/node/pull/60139/](https://ci.nodejs.org/job/node-test-pull-request/69832/)) |
| Appeared | [vm-usrrc](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67479/console), [test-azure_msft-win10_vs2019-x64-4](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win10-COMPILED_BY-vs2022_clang/37328/console), [test-azure_msft-win11_vs2022-x64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win11-COMPILED_BY-vs2022_clang/37328/console), [test-rackspace-win2019_vs2019-x64-1](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2019-COMPILED_BY-vs2022_clang/37328/console), [test-rackspace-win2022_vs2022-x64-5](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=0,nodes=win2022-COMPILED_BY-vs2022_clang/37328/console), [test-azure_msft-win11_vs2022-arm64-3](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/37328/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69810/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69832/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67479/console">Example</a></summary>

```
not ok 4407 parallel/test-watch-mode-kill-signal-override
  ---
  duration_ms: 120084.24800
  severity: fail
  exitcode: -15
  stack: |-
    timeout
  ...

```
</details>

-------

| Reason | <code>wpt/test-hr-time</code> |
| - | :- |
| Type | JS_TEST_FAILURE |
| Failed PR | 2 ([https://github.com/nodejs/node/pull/60266/](https://ci.nodejs.org/job/node-test-pull-request/69787/), [https://github.com/nodejs/node/pull/60271/](https://ci.nodejs.org/job/node-test-pull-request/69803/)) |
| Appeared | [vm-5wwhg](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67447/console), [test-azure_msft-win11_vs2022-arm64-2](https://ci.nodejs.org/job/node-test-binary-windows-js-suites/RUN_SUBSET=1,nodes=win11-arm64-COMPILED_BY-vs2022_clang-arm64/37316/console), [vm-oiqpl](https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67401/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69787/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69803/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-commit-osx/nodes=macos15-x64/67447/console">Example</a></summary>

```
not ok 4806 wpt/test-hr-time
  ---
  duration_ms: 2335.93000
  severity: fail
  exitcode: 1
  stack: |-
    [SKIPPED] idlharness-shadowrealm.window.js: ShadowRealm support is not enabled
    [SKIPPED] window-worker-timeOrigin.window.js: depends on URL.createObjectURL(blob)
    [PASS] self.performance.now() is a function that returns a number
    [PASS] self.performance.now() returns a positive number
    [PASS] self.performance.now() difference is not negative
    [PASS] Performance interface extends EventTarget.
    [PASS] self.performance.now() returns a positive number
    [PASS] self.performance.now() difference is not negative
    [PASS] idl_test validation
    [PASS] Partial interface mixin WindowOrWorkerGlobalScope: original interface mixin defined
    [PASS] Partial interface mixin WindowOrWorkerGlobalScope: member names are unique
    [PASS] Partial interface Window: member names are unique
    [PASS] Window includes GlobalEventHandlers: member names are unique
    [PASS] Window includes WindowEventH...
```
</details>

-------


### Build Failure

| Reason | <code>fatal: No rebase in progress?</code> |
| - | :- |
| Type | BUILD_FAILURE |
| Failed PR | 5 ([https://github.com/nodejs/node/pull/60271/](https://ci.nodejs.org/job/node-test-pull-request/69754/), [https://github.com/nodejs/node/pull/60230/](https://ci.nodejs.org/job/node-test-pull-request/69791/), [https://github.com/nodejs/node/pull/60255/](https://ci.nodejs.org/job/node-test-pull-request/69805/), [https://github.com/nodejs/node/pull/60289/](https://ci.nodejs.org/job/node-test-pull-request/69809/), [https://github.com/nodejs/node/pull/60298/](https://ci.nodejs.org/job/node-test-pull-request/69810/)) |
| Appeared | [test-mnx-ubuntu2204-x64-1](https://ci.nodejs.org/job/node-test-linter/62233/console), [test-ibm-ubuntu2404_sharedlibs_container-x64-5](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_shared_x64/53211/console), [test-ibm-ubuntu2404_sharedlibs_container-x64-4](https://ci.nodejs.org/job/node-test-commit-linux-containered/nodes=ubuntu2404_sharedlibs_shared_x64/53186/console) |
| First CI | https://ci.nodejs.org/job/node-test-pull-request/69754/ |
| Last CI | https://ci.nodejs.org/job/node-test-pull-request/69810/ |

<details>
<summary><a href="https://ci.nodejs.org/job/node-test-linter/62233/console">Example</a></summary>

```
fatal: No rebase in progress?
```
</details>

-------

